export type LanguageOption = {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
};

export const LANGUAGE_OPTIONS: LanguageOption[] = [
  { code: "en", name: "Английский", nativeName: "English", flag: "🇬🇧" },
  { code: "de", name: "Немецкий", nativeName: "Deutsch", flag: "🇩🇪" },
  { code: "es", name: "Испанский", nativeName: "Español", flag: "🇪🇸" },
  { code: "fr", name: "Французский", nativeName: "Français", flag: "🇫🇷" },
  { code: "pt", name: "Португальский", nativeName: "Português", flag: "🇵🇹" },
  { code: "it", name: "Итальянский", nativeName: "Italiano", flag: "🇮🇹" },
  { code: "nl", name: "Нидерландский", nativeName: "Nederlands", flag: "🇳🇱" },
  { code: "pl", name: "Польский", nativeName: "Polski", flag: "🇵🇱" },
  { code: "ru", name: "Русский", nativeName: "Русский", flag: "🇷🇺" },
  { code: "uk", name: "Украинский", nativeName: "Українська", flag: "🇺🇦" },
  { code: "be", name: "Белорусский", nativeName: "Беларуская", flag: "🇧🇾" },
  { code: "cs", name: "Чешский", nativeName: "Čeština", flag: "🇨🇿" },
  { code: "sk", name: "Словацкий", nativeName: "Slovenčina", flag: "🇸🇰" },
  { code: "sl", name: "Словенский", nativeName: "Slovenščina", flag: "🇸🇮" },
  { code: "hr", name: "Хорватский", nativeName: "Hrvatski", flag: "🇭🇷" },
  { code: "sr", name: "Сербский", nativeName: "Српски", flag: "🇷🇸" },
  { code: "bs", name: "Боснийский", nativeName: "Bosanski", flag: "🇧🇦" },
  { code: "bg", name: "Болгарский", nativeName: "Български", flag: "🇧🇬" },
  { code: "ro", name: "Румынский", nativeName: "Română", flag: "🇷🇴" },
  { code: "hu", name: "Венгерский", nativeName: "Magyar", flag: "🇭🇺" },
  { code: "el", name: "Греческий", nativeName: "Ελληνικά", flag: "🇬🇷" },
  { code: "tr", name: "Турецкий", nativeName: "Türkçe", flag: "🇹🇷" },
  { code: "sq", name: "Албанский", nativeName: "Shqip", flag: "🇦🇱" },
  { code: "da", name: "Датский", nativeName: "Dansk", flag: "🇩🇰" },
  { code: "sv", name: "Шведский", nativeName: "Svenska", flag: "🇸🇪" },
  { code: "no", name: "Норвежский", nativeName: "Norsk", flag: "🇳🇴" },
  { code: "fi", name: "Финский", nativeName: "Suomi", flag: "🇫🇮" },
  { code: "is", name: "Исландский", nativeName: "Íslenska", flag: "🇮🇸" },
  { code: "et", name: "Эстонский", nativeName: "Eesti", flag: "🇪🇪" },
  { code: "lv", name: "Латышский", nativeName: "Latviešu", flag: "🇱🇻" },
  { code: "lt", name: "Литовский", nativeName: "Lietuvių", flag: "🇱🇹" },
  { code: "ga", name: "Ирландский", nativeName: "Gaeilge", flag: "🇮🇪" },
  { code: "cy", name: "Валлийский", nativeName: "Cymraeg", flag: "🏴" },
  { code: "ca", name: "Каталанский", nativeName: "Català", flag: "🇪🇸" },
  { code: "eu", name: "Баскский", nativeName: "Euskara", flag: "🇪🇸" },
  { code: "gl", name: "Галисийский", nativeName: "Galego", flag: "🇪🇸" },
  { code: "mt", name: "Мальтийский", nativeName: "Malti", flag: "🇲🇹" },
  { code: "ar", name: "Арабский", nativeName: "العربية", flag: "🇸🇦" },
  { code: "he", name: "Иврит", nativeName: "עברית", flag: "🇮🇱" },
  { code: "fa", name: "Персидский", nativeName: "فارسی", flag: "🇮🇷" },
  { code: "ur", name: "Урду", nativeName: "اردو", flag: "🇵🇰" },
  { code: "hi", name: "Хинди", nativeName: "हिन्दी", flag: "🇮🇳" },
  { code: "bn", name: "Бенгальский", nativeName: "বাংলা", flag: "🇧🇩" },
  { code: "pa", name: "Панджаби", nativeName: "ਪੰਜਾਬੀ", flag: "🇮🇳" },
  { code: "gu", name: "Гуджарати", nativeName: "ગુજરાતી", flag: "🇮🇳" },
  { code: "mr", name: "Маратхи", nativeName: "मराठी", flag: "🇮🇳" },
  { code: "ta", name: "Тамильский", nativeName: "தமிழ்", flag: "🇮🇳" },
  { code: "te", name: "Телугу", nativeName: "తెలుగు", flag: "🇮🇳" },
  { code: "kn", name: "Каннада", nativeName: "ಕನ್ನಡ", flag: "🇮🇳" },
  { code: "ml", name: "Малаялам", nativeName: "മലയാളം", flag: "🇮🇳" },
  { code: "ne", name: "Непальский", nativeName: "नेपाली", flag: "🇳🇵" },
  { code: "si", name: "Сингальский", nativeName: "සිංහල", flag: "🇱🇰" },
  { code: "zh", name: "Китайский", nativeName: "中文", flag: "🇨🇳" },
  { code: "ja", name: "Японский", nativeName: "日本語", flag: "🇯🇵" },
  { code: "ko", name: "Корейский", nativeName: "한국어", flag: "🇰🇷" },
  { code: "vi", name: "Вьетнамский", nativeName: "Tiếng Việt", flag: "🇻🇳" },
  { code: "th", name: "Тайский", nativeName: "ไทย", flag: "🇹🇭" },
  { code: "id", name: "Индонезийский", nativeName: "Bahasa Indonesia", flag: "🇮🇩" },
  { code: "ms", name: "Малайский", nativeName: "Bahasa Melayu", flag: "🇲🇾" },
  { code: "tl", name: "Филиппинский", nativeName: "Filipino", flag: "🇵🇭" },
  { code: "my", name: "Бирманский", nativeName: "မြန်မာ", flag: "🇲🇲" },
  { code: "km", name: "Кхмерский", nativeName: "ខ្មែរ", flag: "🇰🇭" },
  { code: "lo", name: "Лаосский", nativeName: "ລາວ", flag: "🇱🇦" },
  { code: "mn", name: "Монгольский", nativeName: "Монгол", flag: "🇲🇳" },
  { code: "kk", name: "Казахский", nativeName: "Қазақша", flag: "🇰🇿" },
  { code: "uz", name: "Узбекский", nativeName: "O‘zbekcha", flag: "🇺🇿" },
  { code: "az", name: "Азербайджанский", nativeName: "Azərbaycan", flag: "🇦🇿" },
  { code: "hy", name: "Армянский", nativeName: "Հայերեն", flag: "🇦🇲" },
  { code: "ka", name: "Грузинский", nativeName: "ქართული", flag: "🇬🇪" },
  { code: "sw", name: "Суахили", nativeName: "Kiswahili", flag: "🇰🇪" },
  { code: "af", name: "Африкаанс", nativeName: "Afrikaans", flag: "🇿🇦" },
  { code: "zu", name: "Зулу", nativeName: "isiZulu", flag: "🇿🇦" },
  { code: "am", name: "Амхарский", nativeName: "አማርኛ", flag: "🇪🇹" },
  { code: "so", name: "Сомалийский", nativeName: "Soomaali", flag: "🇸🇴" },
  { code: "ha", name: "Хауса", nativeName: "Hausa", flag: "🇳🇬" },
  { code: "yo", name: "Йоруба", nativeName: "Yorùbá", flag: "🇳🇬" }
];
